// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

type AssetClass string

const (
	AssetClassEquities    AssetClass = "equities"
	AssetClassFixedIncome AssetClass = "fixed_income"
	AssetClassCommodities AssetClass = "commodities"
	AssetClassEtfs        AssetClass = "etfs"
	AssetClassForex       AssetClass = "forex"
	AssetClassDerivatives AssetClass = "derivatives"
	AssetClassCrypto      AssetClass = "crypto"
)

func (e *AssetClass) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AssetClass(s)
	case string:
		*e = AssetClass(s)
	default:
		return fmt.Errorf("unsupported scan type for AssetClass: %T", src)
	}
	return nil
}

type NullAssetClass struct {
	AssetClass AssetClass
	Valid      bool // Valid is true if AssetClass is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAssetClass) Scan(value interface{}) error {
	if value == nil {
		ns.AssetClass, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AssetClass.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAssetClass) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AssetClass), nil
}

type TradeOrderType string

const (
	TradeOrderTypeMarket    TradeOrderType = "market"
	TradeOrderTypeLimit     TradeOrderType = "limit"
	TradeOrderTypeStop      TradeOrderType = "stop"
	TradeOrderTypeStopLimit TradeOrderType = "stop_limit"
)

func (e *TradeOrderType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TradeOrderType(s)
	case string:
		*e = TradeOrderType(s)
	default:
		return fmt.Errorf("unsupported scan type for TradeOrderType: %T", src)
	}
	return nil
}

type NullTradeOrderType struct {
	TradeOrderType TradeOrderType
	Valid          bool // Valid is true if TradeOrderType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTradeOrderType) Scan(value interface{}) error {
	if value == nil {
		ns.TradeOrderType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TradeOrderType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTradeOrderType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TradeOrderType), nil
}

type TradePurchaseType string

const (
	TradePurchaseTypeCash   TradePurchaseType = "cash"
	TradePurchaseTypeMargin TradePurchaseType = "margin"
)

func (e *TradePurchaseType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TradePurchaseType(s)
	case string:
		*e = TradePurchaseType(s)
	default:
		return fmt.Errorf("unsupported scan type for TradePurchaseType: %T", src)
	}
	return nil
}

type NullTradePurchaseType struct {
	TradePurchaseType TradePurchaseType
	Valid             bool // Valid is true if TradePurchaseType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTradePurchaseType) Scan(value interface{}) error {
	if value == nil {
		ns.TradePurchaseType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TradePurchaseType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTradePurchaseType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TradePurchaseType), nil
}

type TradebookRole string

const (
	TradebookRoleOwner  TradebookRole = "owner"
	TradebookRoleEditor TradebookRole = "editor"
	TradebookRoleReader TradebookRole = "reader"
)

func (e *TradebookRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TradebookRole(s)
	case string:
		*e = TradebookRole(s)
	default:
		return fmt.Errorf("unsupported scan type for TradebookRole: %T", src)
	}
	return nil
}

type NullTradebookRole struct {
	TradebookRole TradebookRole
	Valid         bool // Valid is true if TradebookRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTradebookRole) Scan(value interface{}) error {
	if value == nil {
		ns.TradebookRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TradebookRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTradebookRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TradebookRole), nil
}

type ExitLeg struct {
	ID           uuid.UUID
	TradeID      uuid.UUID
	ExitDate     time.Time
	ExitQuantity decimal.Decimal
	ExitPrice    decimal.Decimal
	ExitFees     decimal.NullDecimal
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type TokenUsageLog struct {
	EventID          uuid.UUID
	UserID           string
	Timestamp        time.Time
	ModelName        string
	PromptTokens     int32
	CompletionTokens int32
	TotalTokens      int32
	Cost             decimal.Decimal
}

type Trade struct {
	ID            uuid.UUID
	TradebookID   uuid.UUID
	IsOpen        bool
	AssetClass    AssetClass
	PurchaseType  TradePurchaseType
	OrderType     TradeOrderType
	EntryDate     time.Time
	Symbol        string
	Currency      string
	EntryQuantity decimal.Decimal
	EntryPrice    decimal.Decimal
	EntryFees     decimal.NullDecimal
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Tradebook struct {
	ID        uuid.UUID
	OwnerID   string
	Title     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type TradebookMember struct {
	TradebookID uuid.UUID
	UserID      string
	Role        TradebookRole
	JoinedAt    time.Time
}

type User struct {
	ID        string
	CreatedAt time.Time
	UpdatedAt time.Time
}
